id: P004413
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2PD20789
  title: ཡང་གཏེར་རྩ་གསུམ་དྲིལ་སྒྲུབ་ཀྱི་འདོན་ཆ་དང་ཟིན་བྲིས།༼རྒྱ་བོད་ཤན་སྦྱར།༽
  author: ''
  volumes:
    2cb9c507840d4144aebdf7fc4acf82c4:
      image_group_id: I2PD20845
      title: ''
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
